<a href="https://colab.research.google.com/github/LinusRosales/T-NPS/blob/main/NPS_GUIDED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# from google.colab import files
# uploaded = files.upload()

In [2]:
import pandas as pd
import re
n = 126

raw_df = pd.read_csv('T-NPS.csv')
df = pd.read_csv('T-NPS.csv', usecols=range(n))
pd.set_option('display.max_columns', None)

In [3]:
df.columns

Index(['Respondent ID', 'Collector ID', 'Start Date', 'End Date', 'IP Address',
       'Email Address', 'First Name', 'Last Name', 'Custom Data 1', 'rq_flag',
       ...
       'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119',
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124',
       'Which bank do you consider as your main primary bank?Aling bangko ang itinuturing mong pangunahing bangko?'],
      dtype='object', length=126)

# Profile Understanding

In [4]:
raw_df.head(1)

,Respondent ID,Collector ID,Start Date,End Date,IP Address,Email Address,First Name,Last Name,Custom Data 1,rq_flag,language,"Before we proceed do you agree to the terms and conditions, and to provide your full, honest, and candid feedback?Bago tayo magpatuloy, sumasang-ayon ka ba sa mga tuntunin at kondisyon at handang magbigay ng iyong buong, tapat, at bukas na feedback?",Please provide the email address where you received this survey invite.(Pakibigay ang email address kung saan mo nareceive ang survey na ito.),Let us know your overall thoughts about GoTyme Bank.Ibahagi sa amin ang iyong overall na opinyon tungkol sa GoTyme Bank.,Which banks do you currently have an account with?Sa aling mga sumusunod bangko/e-wallet ang kasalukuyang mayroon kang account?,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Please select your top 5 primary banks/e-wallet.Piliin ang iyong top 5 na pangunahing bangko/e-wallet.,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Please select your top 3 primary banks/e-wallet.Piliin ang iyong top 3 na pangunahing bangko/e-wallet.,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,How much is your usual balance in each bank?Magkano ang usual balance na nilalagay mo sa bawat bangko?,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,"How much do you usually spend per month using your primary bank? (Include expenses like bills payment, transfers, online/offline purchases, subscriptions, etc.)Magkano ang karaniwan mong ginagastos bawat buwan gamit ang iyong pangunahing bangko?",Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,"How many transactions do you perform per month using your primary bank? (Include fund transfers, ATM withdrawals, bills payments, purchases, loan payments, etc.)Ilang transaksyon ang karaniwan mong ginagawa bawat buwan gamit ang iyong pangunahing bangko?",Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Which bank do you consider as your main primary bank?Aling bangko ang itinuturing mong pangunahing bangko?,How do you define your primary bank? (Select all that apply)Paano mo inilalarawan ang iyong pangunahing bangko?,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Please rate GoTyme Bank based on the following criteria.(Paki-rate ang GoTyme base sa mga sumusunod na criteria.),Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,How likely are you going to recommend GoTyme Bank to your friends and family based on its usefulness?(Gaano mo i-rerecommend ang GoTyme Bank sa iyong friends o family base sa usefulness nito?),Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,How likely are you going to recommend GoTyme Bank to your friends and family based on its ease of use?(Gaano mo i-rerecommend ang GoTyme Bank sa iyong friends o family base sa dali ng pag gamit dito?),Unnamed: 144,Unnamed: 145,Unnamed: 146,How likely are you going to recommend GoTyme Bank to your friends and family based on its security?(Gaano mo i-rerecommend ang GoTyme Bank sa iyong friends o family base sa kung gaano ito ka-secure?),Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,"Have you ever encountered any security-related issues with GoTyme Bank? (e.g. unauthorized transaction, scam, unauthorized access, etc.)(Nakaranas ka na ba ng security-related issues sa GoTyme Bank?)",How likely is it that you would recommend GoTyme Bank to a friend or colleague?,Which type of interactions have you done with GoTyme Bank for the last 3 months?(Alin sa mga sumusunod na interaction ang nagawa mo sa nakaraang tatlong buwan?),Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,How likely are you to recommend GoTyme Bank to your friends and family based on the following Shop features:(Gaano mo irerekomenda ang GoTyme Bank sa iyong mga kaibigan at pamilya batay sa mga sumusunod na shop features?),Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,"How likely are you going to recommend GoTyme Bank to your friends and family based on Move Money features: (Cash-in/Cash out, Deposit, Withdraw, Send Money via Instapay, Pesonet, Cheque Deposit etc.)(Gaano mo i-rerecommend ang GoTyme Bank sa iyong friends o family base move money features?)",Unnamed: 168,Unnamed: 169,Unnamed: 170,How likely are you to recommend GoTyme Bank to your friends and family based on the following Savings features:(Gaano mo irerekomenda ang GoTyme Bank sa iyong mga kaibigan at pamilya batay sa mga sumusunod na shop features?),Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,How likely are you to recommend GoTyme Bank to your friends and family based on the following Payroll features:(Gaano mo irerekomenda ang GoTyme Bank sa iyong mga kaibigan at pamilya batay sa mga sumusunod na Payroll features?),Unnamed: 177,Unnamed: 178,Unnamed: 179,How likely are you to recommend GoTyme Bank to your friends and family based on the following BNPL features:(Gaano mo irerekomenda ang GoTyme Bank sa iyong mga kaibigan at pamilya batay sa mga sumusunod na BNPL features?),Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,How likely are you going to recommend GoTyme Bank to your friends and family based on your customer service experience?(Gaano mo i-rerecommend ang GoTyme Bank sa iyong friends o family base iyong customer service experience?),Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,What did you do to resolve your issue/concern in GoTyme Bank?(Ano ang ginawa mo para ma-resolve ang issue o concern mo sa GoTyme Bank?)Check all that is applicable,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Was your issue or concern resolved?(Na-resolve ba ang issue o concern mo?),"In the past 7 days, have you interacted with GoTyme Bank on the comment section in any of our official social media pages (e.g. Facebook, X, Instagram)?(Nitong nakaraang 7 araw, nag-comment ka ba sa official social media pages ng GoTyme Bank tulad ng Facebook, X, o Instagram?)",Which of these describe you before opening a GoTyme Bank account?(Alin sa mga ito ang naglalarawan sa 'yo bago ka magbukas ng GoTyme Bank account?),Primary source of personal income(Pangunahing pinagmumulan ng personal mong kita),How much is your gross monthly personal income?(Magkano ang iyong buwanang kita?),Where are you currently located?(Saan ka kasalukuyang nakatira?)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Response,Open-Ended Response,Open-Ended Response,None of the above,BDO Unibank,BPI (Bank of the Philippine Islands),Metrobank,Land Bank of the Philippines,Security Bank,UnionBank,RCBC (Rizal Commercial Banking Corporation),China Bank,PNB (Philippine National Bank),EastWest Bank,GoTyme Bank,Maya Bank,Tonik Bank,CIMB Bank,"Overseas Bank (e.g., HSBC, Citibank, Standard ...",Seabank,OwnBank,GCash,None of the above,BDO Unibank,BPI (Bank of the Philippine Islands),Metrobank,Land Bank of the Philippines,Security Bank,UnionBank,RCBC (Rizal Commercial Banking Corporation),China Bank,PNB (Philippine National Bank),EastWest Bank,GoTyme Bank,Maya Bank,Tonik Bank,CIMB Bank,"Overseas Bank (e.g., HSBC, Citibank, Standard ...",Seabank,OwnBank,GCash,None of the above,BDO Unibank,BPI (Bank of the Philippine Islands),Metrobank,Land Bank of the Philippines,Security Bank,UnionBank,RCBC (Rizal Commercial Banking Corporation),China Bank,PNB (Philippine National Bank),EastWest Bank,GoTyme Bank,Maya Bank,Tonik Bank,CIMB Bank,"Overseas Bank (e.g., HSBC, Citibank, Standard ...",Seabank,OwnBank,GCash,BDO Unibank,BPI (Bank of the Philippine Islands),Metrobank,Land Bank of the Philippines,Security Bank,UnionBank,RCBC (Rizal Commercial Banking Corporation),China Bank,PNB (Philippine National Bank),EastWest Bank,GoTyme Bank,Maya Bank,Tonik Bank,CIMB Bank,"Overseas Bank (e.g., HSBC, Citibank, Standard ...",Seabank,OwnBank,GCash,BDO Unibank,BPI (Bank of the Philippine Islands),Metrobank,Land Bank of the Philippines,Security Bank,UnionBank,RCBC (Rizal Commercial Banking Corporation),China Bank,PNB (Philippine National Bank),EastWest Bank,GoTyme Bank,Maya Bank,Tonik Bank,CIMB Bank,"Overseas Bank (e.g., HSBC, Citibank, Standard ...",Seabank,OwnBank,GCash,BDO Unibank,BPI (Bank of the Philippine Islands),Metrobank,Land Bank of the Philippines,Security Bank,UnionBank,RCBC (Rizal Commercial Banking Corporation),China Bank,PNB (Philippine National Bank),EastWest Bank,GoTyme Bank,Maya Bank,Tonik Bank,CIMB Bank,"Overseas Bank (e.g., HSBC, Citibank, Standard ...",Seabank,OwnBank,GCash,Response,It’s the bank where I keep the most money.Ito ...,It’s the bank I use the most for everyday tran...,It’s the bank where my salary or main income i...,It’s the bank where I have my loans or credit ...,It’s the bank I use for international transact...,It’s the bank I use for business banking or ma...,It’s the bank I trust the most for financial s...,I am satisfied in my overall experience with G...,I strongly prefer GoTyme Bank over other banks...,I am going to continue using GoTyme Bank in th...,I feel SECURED whenever I use GoTyme Bank.(Sec...,I TRUST GoTyme Bank with my financial transact...,Overall Usefulness of GoTyme Bank.(Pang kalaha...,It has various products and services which are...,Always available with no downtime whenever I n...,Has a wide range of online and offline partner...,Convenient than offline payment methods (e.g. ...,Mobile app is intuitive and user-friendly.(Mob...,App is easy to navigate and get used to.(Ang a...,The app and kiosk instructions are clear and e...,I find the app reliable and free from technica...,Overall security of account and transactions w...,Sufficient security features to help me protec...,Transparency on how my data is protected with ...,Assurance that my funds stay intact in my acco...,Secure based on security-related feedback that...,I get helpful information to protect my accoun...,Response,Response,None of the above,"Shop (e.g. Card Swipe or Tap, Online Transacti...","Move Money (e.g. Send Money, Cheque Deposit, C...","Save (e.g. GoSave, Time Deposit)",Payroll (e.g. received my money or allowance v...,Lend (e.g. BNPL MoreTyme),Service (e.g. Contacted Customer Service via I...,Overall satisfaction with shop transactions.(P...,Availability of relevant Billers and Load Merc...,Seamlessness of Debit Card use in online and r...,Reliability of Debit Card use in online and re...,Rewards earned whenever Debit Card is used for...,Overall satisfaction on my move money experien...,Instapay or Pesonet experience is seamless and...,Reliability of sending money via Instapay or P...,Hassle free and convenient deposit and withdra...,Overall satisfaction with savings security and...,Ease and convenience to save money.(Dali at co...,Meeting savings needs and expectations.(Pagtug...,Competitiveness of interest rate.(Competitive ...,Direct and easy moving of funds from GoSave to...,Reliability of Salary Credit (Timely and accur...,"Ease of Access to Salary (Withdrawals, transfe...",Customer Support for Payroll Concerns (Respons...,"Overall Payroll Experience (Seamlessness, con...",Ease of Use (Seamless activation and usage of ...,Approval Process (Speed and simplicity of gett...,Payment Flexibility (Convenience of installmen...,"Fees and Charges (Fairness of interest rates, ...",Checkout Experience at Merchants (Ease of usin...,Overall MoreTyme Experience (Satisfaction with...,GoTyme Bank has great customer service based o...,Content and frequency of updates provided by G...,"Easy to get help, connect to contact center, a...",Issues are resolved in a timely manner.(Mabili...,Issues are instantly resolved by the customer ...,Personal Bankers are sincere and assuring.(Ang...,Customer service of GoTyme Bank is the best in...,None of the above,Chatted with a live agent.(Nakipag-chat sa isa...,Sent an email.(Nag-send ng email.),Posted a comment on the official social media ...,Called #GO8888.(Tumawag sa #GO8888.),Posted my issue or concern publicly on social ...,Directly escalated my concern to BSP or any re...,Did not reach out to GoTyme Bank’s customer se...,Response,Response,Response,Response,Response,Response

**Rename/remove tagalog question**

In [5]:
df = df.rename(columns={
    'Before we proceed do you agree to the terms and conditions, and to provide your full, honest, and candid feedback?Bago tayo magpatuloy, sumasang-ayon ka ba sa mga tuntunin at kondisyon at handang magbigay ng iyong buong, tapat, at bukas na feedback?':
        'Before we proceed do you agree to the terms and conditions, and to provide your full, honest, and candid feedback?',

    'Please provide the email address where you received this survey invite.(Pakibigay ang email address kung saan mo nareceive ang survey na ito.)':
        'Please provide the email address where you received this survey invite.',

    'Let us know your overall thoughts about GoTyme Bank.Ibahagi sa amin ang iyong overall na opinyon tungkol sa GoTyme Bank.':
        'Let us know your overall thoughts about GoTyme Bank.',

    'Which banks do you currently have an account with?Sa aling mga sumusunod bangko/e-wallet ang kasalukuyang mayroon kang account?':
        'Which banks do you currently have an account with?',

    'Please select your top 5 primary banks/e-wallet.Piliin ang iyong top 5 na pangunahing bangko/e-wallet.':
        'Please select your top 5 primary banks/e-wallet.',

    'Please select your top 3 primary banks/e-wallet.Piliin ang iyong top 3 na pangunahing bangko/e-wallet.':
        'Please select your top 3 primary banks/e-wallet.',

    'How much is your usual balance in each bank?Magkano ang usual balance na nilalagay mo sa bawat bangko?':
        'How much is your usual balance in each bank?',

    'How much do you usually spend per month using your primary bank? (Include expenses like bills payment, transfers, online/offline purchases, subscriptions, etc.)Magkano ang karaniwan mong ginagastos bawat buwan gamit ang iyong pangunahing bangko?':
        'How much do you usually spend per month using your primary bank? (Include expenses like bills payment, transfers, online/offline purchases, subscriptions, etc.)',

    'How many transactions do you perform per month using your primary bank? (Include fund transfers, ATM withdrawals, bills payments, purchases, loan payments, etc.)Ilang transaksyon ang karaniwan mong ginagawa bawat buwan gamit ang iyong pangunahing bangko?':
        'How many transactions do you perform per month using your primary bank? (Include fund transfers, ATM withdrawals, bills payments, purchases, loan payments, etc.)',

    'Which bank do you consider as your main primary bank?Aling bangko ang itinuturing mong pangunahing bangko?':
        'Which bank do you consider as your main primary bank?'
})

In [6]:
df.columns

Index(['Respondent ID', 'Collector ID', 'Start Date', 'End Date', 'IP Address',
       'Email Address', 'First Name', 'Last Name', 'Custom Data 1', 'rq_flag',
       ...
       'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119',
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124',
       'Which bank do you consider as your main primary bank?'],
      dtype='object', length=126)

**Remove unnecessary columns**

In [7]:
df.drop(columns=['Email Address', 'First Name', 'Last Name', 'Custom Data 1'], inplace=True)

**Respondent ID to str**

In [8]:
df['Respondent ID'] = df['Respondent ID'].astype(str)

**Forward Fill columns**

In [9]:
from collections import defaultdict

def clean_and_merge_columns(df):
    # Step 1: Fix unnamed or blank columns
    df.columns = [col if not (pd.isna(col) or str(col).startswith("Unnamed")) else None for col in df.columns]
    df.columns = pd.Series(df.columns).fillna(method='ffill')

    # return new_df
    return "forward filled columns"

In [10]:
clean_and_merge_columns(df)

/tmp/ipython-input-9-1653649604.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.columns = pd.Series(df.columns).fillna(method='ffill')

'forward filled columns'

**Combine column header and first row of data**

In [11]:

    # Extract the first row as a list
label_row = df.iloc[0].tolist()

    # Build new column names by combining column header and label
new_columns = []
for col, label in zip(df.columns, label_row):
      col_str = str(col).strip()
      label_str = str(label).strip() if pd.notna(label) and str(label).strip().lower() != "nan" else ""

      if label_str:
          new_col = f"{col_str} - {label_str}"
      else:
          new_col = col_str

      new_columns.append(new_col)

    # Apply new column names
df.columns = new_columns

    # Drop the label row
df = df.iloc[1:].reset_index(drop=True)

    # Optional: Try converting columns to numeric where appropriate
df = df.apply(pd.to_numeric, errors='ignore')

/tmp/ipython-input-11-4177289625.py:24: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

**Understand null**

In [12]:
pd.set_option('display.max_rows', None)

In [13]:
print(len(df))

2846

**Understand null of rq_flag**

In [14]:
df['rq_flag'].value_counts()

rq_flag
0.0    2270
1.0     532
Name: count, dtype: int64

In [15]:
print("Keep rq_flag")

Keep rq_flag

**Fill Null of first 122 columns**

In [16]:
df.iloc[:, :122] = df.iloc[:, :122].fillna("")
pass

/tmp/ipython-input-16-2491489263.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      1.0
13      0.0
14      0.0
15      0.0
16      0.0
17
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      1.0
28      0.0
29      0.0
30      1.0
31      0.0
32      0.0
33      0.0
34      0.0
35      0.0
36      0.0
37      0.0
38      0.0
39      0.0
40      0.0
41      0.0
42      0.0
43      0.0
44      0.0
45      0.0
46      0.0
47      0.0
48      0.0
49      0.0
50      0.0
51      0.0
52      0.0
53      0.0
54      0.0
55      0.0
56      0.0
57      0.0
58      0.0
59      0.0
60      0.0
61      0.0
62      0.0
63      0.0
64      0.0
65      0.0
66      0.0
67      1.0
68      0.0
69      0.0
70      0.0
71      0.0
72      0.0
73      0.0
74      0.0
75      1.0
76      0.0
77      0.0
78      0.0
79      0.0
80      1.0
81      0.0
82      1.0
83      0.0
84      0.0
85      0.0
86      0.0
87      0.0
88      0.0
89      0.0
90      0.0
91      0.0
92      0.0
93      0.0
94      0.0
95      0.0
96      1.0
97      0.0
98      0.0
99      1.0
100     0.0
101     0.0
102     1.0
103     1.0
104     0.0
105     0.0
106     0.0
107     0.0
108     0.0
109     0.0
110     0.0
111     0.0
112     0.0
113     0.0
114     0.0
115     0.0
116     0.0
117     0.0
118     1.0
119     0.0
120     0.0
121     0.0
122     0.0
123     0.0
124     0.0
125     0.0
126     0.0
127     1.0
128     0.0
129     1.0
130     0.0
131     0.0
132     0.0
133     1.0
134     0.0
135     0.0
136     0.0
137     0.0
138     0.0
139     0.0
140     0.0
141     0.0
142     1.0
143     0.0
144     0.0
145     0.0
146     1.0
147     0.0
148     0.0
149     0.0
150     0.0
151     0.0
152     0.0
153     0.0
154     0.0
155     0.0
156     0.0
157     0.0
158     0.0
159     1.0
160     0.0
161     1.0
162     1.0
163     0.0
164
165     0.0
166     0.0
167     1.0
168     1.0
169     0.0
170     1.0
171     0.0
172     0.0
173     0.0
174     0.0
175     1.0
176     0.0
177     0.0
178     0.0
179     0.0
180     0.0
181     0.0
182     1.0
183     0.0
184     1.0
185     0.0
186     1.0
187     0.0
188     0.0
189     0.0
190     0.0
191     0.0
192     0.0
193     0.0
194     0.0
195     0.0
196     0.0
197     0.0
198     0.0
199     0.0
200     0.0
201     0.0
202     0.0
203     0.0
204     0.0
205     0.0
206     1.0
207     0.0
208     0.0
209     1.0
210     0.0
211     0.0
212     0.0
213     0.0
214     0.0
215     0.0
216     0.0
217     0.0
218     0.0
219     0.0
220     1.0
221     0.0
222     0.0
223     0.0
224     0.0
225     0.0
226     0.0
227     0.0
228     0.0
229     0.0
230     0.0
231     0.0
232     0.0
233     0.0
234     0.0
235     0.0
236     0.0
237     0.0
238     0.0
239     0.0
240     0.0
241     0.0
242     0.0
243     0.0
244     1.0
245     1.0
246     0.0
247     0.0
248     0.0
249     0.0
250     0.0
251     1.0
252     0.0
253     0.0
254     0.0
255     0.0
256     0.0
257     0.0
258     0.0
259     0.0
260     0.0
261     1.0
262     0.0
263     1.0
264     0.0
265     0.0
266     0.0
267     0.0
268     0.0
269     0.0
270     1.0
271     0.0
272     0.0
273     0.0
274     0.0
275     1.0
276     1.0
277     0.0
278     0.0
279     0.0
280     1.0
281     0.0
282     1.0
283     0.0
284     0.0
285     0.0
286     0.0
287     0.0
288     0.0
289     1.0
290     0.0
291     0.0
292     0.0
293     1.0
294     0.0
295     0.0
296     0.0
297     0.0
298     0.0
299     1.0
300     0.0
301     1.0
302     0.0
303     1.0
304     0.0
305     0.0
306     0.0
307     0.0
308     1.0
309     1.0
310     0.0
311     1.0
312     0.0
313     0.0
314     0.0
315     0.0
316     0.0
317     0.0
318     0.0
319     1.0
320     0.0
321     1.0
322     1.0
323     0.0
324     0.0
325     0.0
326     1.0
327     0.0
328     0.0
329     0.0
330     1.0
331     0.0
332     0.0
333     1.0
334     0.0
335     0.0
336     0.0
337     0.0
338     0.0
339     0.0
340     0.0
341     1.0
342     0.0
343     0.0
344     0.0
345     0.0
346     0.0
347     0.0
348     0.0
349     0.0
350
351     0.0
352
353     0.0
354     0.0
355     1.0
356     0.0
357     0.0
358     0.0
359     0.0
360     0.0
361     0.0
362     1.0
363     0.0
364     0.0
365     1.0
366     0.0
367     0.0
368     1.0
369     0.0
370     0.0
371     1.0
372
373     0.0
374     0.0
375     0.0
376     0.0
377     1.0
378     0.0
379     0.0
380     0.0
381     0.0
382     0.0
383     1.0
384     0.0
385     0.0
386     0.0
387     0.0
388     0.0
389     0.0
390     0.0
391     0.0
392     0.0
393     0.0
394     0.0
395     0.0
396     0.0
397     0.0
398     1.0
399     0.0
400     0.0
401     0.0
402     0.0
403     0.0
404     0.0
405     0.0
406     0.0
407     0.0
408     0.0
409     1.0
410     0.0
411     0.0
412     0.0
413     1.0
414     0.0
415     0.0
416     0.0
417     0.0
418     0.0
419     0.0
420     0.0
421     0.0
422     0.0
423     0.0
424     0.0
425     0.0
426     0.0
427     0.0
428     0.0
429     0.0
430     0.0
431     1.0
432     0.0
433     1.0
434     0.0
435     0.0
436     0.0
437     0.0
438     1.0
439     0.0
440     0.0
441     0.0
442     1.0
443     1.0
444     0.0
445     0.0
446     0.0
447     0.0
448     1.0
449     0.0
450     0.0
451     1.0
452     0.0
453     1.0
454     0.0
455     0.0
456     0.0
457     0.0
458     1.0
459     0.0
460     0.0
461     0.0
462     0.0
463     0.0
464     0.0
465     0.0
466     0.0
467     0.0
468     0.0
469     0.0
470     0.0
471     0.0
472     0.0
473     0.0
474     1.0
475     0.0
476     0.0
477     0.0
478     1.0
479     0.0
480     0.0
481     1.0
482     0.0
483     1.0
484     0.0
485     0.0
486     0.0
487     0.0
488     0.0
489     0.0
490     0.0
491     0.0
492     1.0
493     0.0
494     1.0
495     0.0
496     0.0
497     0.0
498     0.0
499     0.0
500     0.0
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
506     0.0
507     1.0
508     0.0
509     0.0
510     0.0
511     0.0
512     0.0
513     1.0
514     1.0
515     0.0
516     0.0
517     0.0
518     0.0
519     0.0
520     0.0
521     0.0
522     1.0
523     1.0
524     0.0
525     0.0
526     0.0
527     0.0
528     0.0
529     1.0
530     1.0
531     0.0
532     0.0
533     1.0
534     0.0
535     0.0
536     0.0
537     1.0
538     1.0
539     0.0
540     1.0
541     0.0
542     1.0
543     0.0
544     0.0
545     0.0
546     0.0
547     0.0
548     1.0
549     0.0
550     0.0
551     0.0
552     0.0
553     1.0
554     0.0
555     0.0
556     0.0
557     0.0
558     0.0
559     0.0
560     0.0
561     0.0
562     0.0
563     0.0
564     1.0
565     1.0
566     0.0
567     0.0
568     0.0
569     0.0
570     0.0
571     0.0
572     0.0
573     0.0
574     0.0
575     1.0
576     0.0
577     0.0
578     0.0
579     0.0
580     0.0
581     0.0
582     1.0
583     0.0
584     0.0
585     0.0
586     0.0
587     0.0
588     0.0
589     0.0
590     0.0
591     0.0
592     0.0
593     0.0
594     0.0
595     0.0
596     1.0
597     0.0
598     0.0
599     0.0
600     0.0
601     1.0
602     0.0
603     0.0
604
605     0.0
606     1.0
607     0.0
608     0.0
609     1.0
610     1.0
611     1.0
612     0.0
613     0.0
614     0.0
615     1.0
616     0.0
617     0.0
618     0.0
619     1.0
620     0.0
621     0.0
622     0.0
623     1.0
624     0.0
625     0.0
626     0.0
627     0.0
628     0.0
629     0.0
630     0.0
631     0.0
632     0.0
633     0.0
634     0.0
635     0.0
636     0.0
637     0.0
638     1.0
639     0.0
640     0.0
641     0.0
642     1.0
643     0.0
644     0.0
645     0.0
646     0.0
647     1.0
648     0.0
649     0.0
650     0.0
651     0.0
652     0.0
653     0.0
654     0.0
655     0.0
656     0.0
657     0.0
658     1.0
659     0.0
660     0.0
661     0.0
662     0.0
663     0.0
664     0.0
665     0.0
666     0.0
667     0.0
668     0.0
669     0.0
670     0.0
671     1.0
672     0.0
673     1.0
674     0.0
675     0.0
676     0.0
677     0.0
678     0.0
679     1.0
680     0.0
681     0.0
682     0.0
683     0.0
684     0.0
685     0.0
686     0.0
687     0.0
688     0.0
689     1.0
690     0.0
691     0.0
692     0.0
693     0.0
694     0.0
695     0.0
696     1.0
697     0.0
698     0.0
699     0.0
700     0.0
701     0.0
702     0.0
703     0.0
704     0.0
705     0.0
706     0.0
707     0.0
708     0.0
709     0.0
710     0.0
711     0.0
712     0.0
713     0.0
714     0.0
715     1.0
716     1.0
717     0.0
718     0.0
719     1.0
720     1.0
721     0.0
722     0.0
723     0.0
724     0.0
725     0.0
726     0.0
727
728     1.0
729     0.0
730     0.0
731     0.0
732     1.0
733     0.0
734     0.0
735     1.0
736     0.0
737     0.0
738     0.0
739     0.0
740     0.0
741     0.0
742     0.0
743     0.0
744     0.0
745     0.0
746     0.0
747     0.0
748     0.0
749     1.0
750     0.0
751     0.0
752     0.0
753     1.0
754     0.0
755     0.0
756     0.0
757     0.0
758     0.0
759     0.0
760     0.0
761     0.0
762     0.0
763     0.0
764     1.0
765     0.0
766     0.0
767     0.0
768     0.0
769     0.0
770     0.0
771     0.0
772     0.0
773     0.0
774     0.0
775     0.0
776     0.0
777     0.0
778     0.0
779     0.0
780     0.0
781     0.0
782     0.0
783     0.0
784     0.0
785     0.0
786     0.0
787     0.0
788     0.0
789     0.0
790     1.0
791     1.0
792     0.0
793     0.0
794     0.0
795     0.0
796     0.0
797     0.0
798     0.0
799     1.0
800     0.0
801     0.0
802
803
804     0.0
805     0.0
806
807     0.0
808     0.0
809     0.0
810     0.0
811     0.0
812     0.0
813     0.0
814     0.0
815     1.0
816     1.0
817     0.0
818     0.0
819     1.0
820     1.0
821     0.0
822     0.0
823     0.0
824     0.0
825     1.0
826     1.0
827     0.0
828     1.0
829     0.0
830     0.0
831     0.0
832     0.0
833     1.0
834     0.0
835     0.0
836     0.0
837     0.0
838     0.0
839     0.0
840     0.0
841     0.0
842     0.0
843     0.0
844     0.0
845     0.0
846     0.0
847     1.0
848     0.0
849     0.0
850     1.0
851     0.0
852     0.0
853     0.0
854     0.0
855     0.0
856     1.0
857     0.0
858     0.0
859     0.0
860     0.0
861     0.0
862     1.0
863     0.0
864     0.0
865     0.0
866     0.0
867     0.0
868     0.0
869     0.0
870     0.0
871     0.0
872     0.0
873     0.0
874     0.0
875     0.0
876     0.0
877     0.0
878     0.0
879     0.0
880     0.0
881     0.0
882     0.0
883     0.0
884     1.0
885     0.0
886     1.0
887     0.0
888     0.0
889     0.0
890     1.0
891     0.0
892     1.0
893     0.0
894     0.0
895     0.0
896     0.0
897     0.0
898     0.0
899     0.0
900     0.0
901     0.0
902     0.0
903     0.0
904     0.0
905     0.0
906     0.0
907     1.0
908     1.0
909     0.0
910     0.0
911     0.0
912     0.0
913     0.0
914     0.0
915     0.0
916     0.0
917     0.0
918     1.0
919     0.0
920     1.0
921     0.0
922     0.0
923     1.0
924     0.0
925     0.0
926     0.0
927     0.0
928     0.0
929     0.0
930     1.0
931     1.0
932     0.0
933     0.0
934     0.0
935     0.0
936     1.0
937     0.0
938     0.0
939     0.0
940     0.0
941     0.0
942     0.0
943     0.0
944     0.0
945     0.0
946     0.0
947     0.0
948     0.0
949     1.0
950     0.0
951     1.0
952     0.0
953     0.0
954     0.0
955
956     0.0
957     0.0
958     0.0
959     0.0
960
961     1.0
962     1.0
963     0.0
964     0.0
965     0.0
966     0.0
967     0.0
968     0.0
969     0.0
970     1.0
971     0.0
972     0.0
973     1.0
974     0.0
975     1.0
976     0.0
977     0.0
978     0.0
979     0.0
980     1.0
981     0.0
982     1.0
983     1.0
984     0.0
985     0.0
986     0.0
987     0.0
988     0.0
989     0.0
990     1.0
991     1.0
992     0.0
993     0.0
994     0.0
995     0.0
996     1.0
997     0.0
998
999     0.0
1000    0.0
1001    1.0
1002    0.0
1003    0.0
1004    1.0
1005    0.0
1006
1007    1.0
1008    0.0
1009    0.0
1010    0.0
1011    0.0
1012    1.0
1013    0.0
1014    0.0
1015    0.0
1016    0.0
1017
1018    0.0
1019    0.0
1020    0.0
1021    0.0
1022    0.0
1023    0.0
1024    0.0
1025    0.0
1026    0.0
1027    0.0
1028    0.0
1029    0.0
1030    0.0
1031    0.0
1032    0.0
1033    0.0
1034    0.0
1035    1.0
1036    0.0
1037    1.0
1038    0.0
1039    0.0
1040    0.0
1041    0.0
1042    1.0
1043    0.0
1044    0.0
1045
1046    0.0
1047    0.0
1048    1.0
1049    0.0
1050    0.0
1051    0.0
1052    1.0
1053    0.0
1054    0.0
1055    1.0
1056    0.0
1057    0.0
1058    0.0
1059    0.0
1060    0.0
1061    0.0
1062    1.0
1063    0.0
1064    0.0
1065    0.0
1066    1.0
1067    0.0
1068    0.0
1069    0.0
1070    1.0
1071    0.0
1072    0.0
1073    0.0
1074    0.0
1075    0.0
1076    0.0
1077    1.0
1078    0.0
1079    0.0
1080    0.0
1081    0.0
1082    0.0
1083    0.0
1084    0.0
1085    1.0
1086    1.0
1087    0.0
1088    0.0
1089    0.0
1090    0.0
1091    0.0
1092    0.0
1093    0.0
1094    1.0
1095    0.0
1096    0.0
1097    0.0
1098    0.0
1099
1100    1.0
1101    0.0
1102    0.0
1103    0.0
1104    1.0
1105    0.0
1106    0.0
1107    0.0
1108    1.0
1109    0.0
1110    0.0
1111    0.0
1112    0.0
1113    0.0
1114    0.0
1115    0.0
1116    0.0
1117    0.0
1118    0.0
1119    0.0
1120    0.0
1121    0.0
1122    0.0
1123    1.0
1124    1.0
1125    0.0
1126    0.0
1127    0.0
1128    0.0
1129    1.0
1130    0.0
1131    1.0
1132    0.0
1133    0.0
1134    0.0
1135    0.0
1136    1.0
1137    0.0
1138    0.0
1139    0.0
1140    0.0
1141    0.0
1142    1.0
1143    0.0
1144    0.0
1145    0.0
1146    0.0
1147    0.0
1148
1149    0.0
1150    0.0
1151    0.0
1152    1.0
1153    0.0
1154
1155    1.0
1156    1.0
1157    0.0
1158    1.0
1159    0.0
1160    0.0
1161
1162    0.0
1163    0.0
1164    0.0
1165    0.0
1166    0.0
1167    0.0
1168    1.0
1169    0.0
1170    0.0
1171    0.0
1172    0.0
1173    0.0
1174    0.0
1175    0.0
1176    0.0
1177    1.0
1178    0.0
1179    0.0
1180    0.0
1181    0.0
1182    0.0
1183    0.0
1184    1.0
1185    0.0
1186    0.0
1187    0.0
1188    0.0
1189    0.0
1190    0.0
1191    1.0
1192    0.0
1193    0.0
1194    0.0
1195    0.0
1196    1.0
1197    0.0
1198    0.0
1199    1.0
1200    0.0
1201    0.0
1202    0.0
1203    0.0
1204    0.0
1205    0.0
1206    0.0
1207    1.0
1208    0.0
1209    0.0
1210    1.0
1211    0.0
1212    0.0
1213    0.0
1214
1215    0.0
1216    0.0
1217    0.0
1218    1.0
1219    1.0
1220    0.0
1221    1.0
1222    1.0
1223    0.0
1224    1.0
1225    0.0
1226    1.0
1227    1.0
1228    0.0
1229    1.0
1230    0.0
1231    0.0
1232    0.0
1233    0.0
1234    0.0
1235    0.0
1236    0.0
1237    0.0
1238    0.0
1239    0.0
1240    0.0
1241    0.0
1242    0.0
1243    1.0
1244    1.0
1245    0.0
1246    0.0
1247    0.0
1248    0.0
1249    0.0
1250    1.0
1251    0.0
1252    0.0
1253    1.0
1254    0.0
1255    0.0
1256    0.0
1257    0.0
1258    0.0
1259    1.0
1260    0.0
1261    0.0
1262    0.0
1263    1.0
1264    0.0
1265    1.0
1266    0.0
1267    0.0
1268    0.0
1269    0.0
1270    0.0
1271    0.0
1272    0.0
1273    0.0
1274
1275    0.0
1276    1.0
1277    0.0
1278    0.0
1279
1280    0.0
1281    0.0
1282    0.0
1283    1.0
1284    0.0
1285    0.0
1286    1.0
1287    0.0
1288    0.0
1289    0.0
1290    0.0
1291    1.0
1292    0.0
1293    0.0
1294    0.0
1295    0.0
1296    1.0
1297    0.0
1298    0.0
1299    0.0
1300    0.0
1301    0.0
1302    0.0
1303    0.0
1304    0.0
1305    0.0
1306    0.0
1307    0.0
1308    1.0
1309    0.0
1310    0.0
1311    0.0
1312    0.0
1313    0.0
1314    0.0
1315    0.0
1316    0.0
1317    0.0
1318    0.0
1319    0.0
1320    0.0
1321    0.0
1322    0.0
1323    0.0
1324    1.0
1325    0.0
1326
1327    0.0
1328    0.0
1329    0.0
1330    1.0
1331    1.0
1332    0.0
1333    1.0
1334    0.0
1335    0.0
1336    0.0
1337    1.0
1338    0.0
1339    0.0
1340    0.0
1341    0.0
1342    0.0
1343    0.0
1344    0.0
1345    0.0
1346    0.0
1347    0.0
1348    0.0
1349    0.0
1350    0.0
1351    1.0
1352    0.0
1353    0.0
1354    1.0
1355    1.0
1356    0.0
1357    0.0
1358    0.0
1359    0.0
1360    0.0
1361
1362    0.0
1363    0.0
1364    0.0
1365    0.0
1366    0.0
1367    0.0
1368    0.0
1369    0.0
1370    0.0
1371    0.0
1372    1.0
1373    0.0
1374    0.0
1375    0.0
1376    0.0
1377    0.0
1378    1.0
1379    0.0
1380    0.0
1381    1.0
1382    0.0
1383    1.0
1384    0.0
1385    0.0
1386    0.0
1387    0.0
1388    0.0
1389    1.0
1390    0.0
1391    0.0
1392    0.0
1393    1.0
1394    0.0
1395    0.0
1396    0.0
1397    0.0
1398    0.0
1399    0.0
1400    0.0
1401    0.0
1402    0.0
1403    0.0
1404    0.0
1405    0.0
1406    0.0
1407    0.0
1408    0.0
1409    0.0
1410    1.0
1411    0.0
1412    0.0
1413    0.0
1414    0.0
1415    0.0
1416    1.0
1417    0.0
1418    0.0
1419    0.0
1420    0.0
1421    0.0
1422    0.0
1423    0.0
1424    0.0
1425
1426    0.0
1427    0.0
1428    0.0
1429    0.0
1430    0.0
1431    0.0
1432    0.0
1433    0.0
1434
1435    0.0
1436    0.0
1437    0.0
1438    0.0
1439    0.0
1440    0.0
1441    0.0
1442    0.0
1443    0.0
1444    1.0
1445    0.0
1446    0.0
1447    0.0
1448    0.0
1449    0.0
1450    0.0
1451    1.0
1452    0.0
1453    1.0
1454    0.0
1455    0.0
1456    0.0
1457    0.0
1458    0.0
1459    0.0
1460    0.0
1461    1.0
1462    1.0
1463    1.0
1464    0.0
1465    0.0
1466    0.0
1467    0.0
1468    1.0
1469    1.0
1470    0.0
1471    1.0
1472    0.0
1473    0.0
1474    1.0
1475
1476    1.0
1477    1.0
1478    0.0
1479    0.0
1480    0.0
1481    0.0
1482    0.0
1483    0.0
1484    0.0
1485    0.0
1486    0.0
1487    0.0
1488    0.0
1489    0.0
1490    1.0
1491    0.0
1492    0.0
1493    0.0
1494    0.0
1495    1.0
1496    0.0
1497    0.0
1498    1.0
1499    0.0
1500    0.0
1501    1.0
1502    0.0
1503    1.0
1504    0.0
1505    0.0
1506    0.0
1507    0.0
1508    0.0
1509    0.0
1510    0.0
1511    1.0
1512    0.0
1513    0.0
1514    0.0
1515    0.0
1516    0.0
1517    0.0
1518    1.0
1519    1.0
1520    0.0
1521    0.0
1522    0.0
1523    0.0
1524    0.0
1525    0.0
1526    0.0
1527    0.0
1528    0.0
1529    0.0
1530    0.0
1531    0.0
1532    0.0
1533    0.0
1534    0.0
1535    0.0
1536    0.0
1537    0.0
1538    1.0
1539    0.0
1540    0.0
1541    0.0
1542    0.0
1543    0.0
1544    0.0
1545    0.0
1546    1.0
1547    0.0
1548    0.0
1549    0.0
1550    0.0
1551    0.0
1552    0.0
1553    0.0
1554    0.0
1555    1.0
1556    0.0
1557    0.0
1558    0.0
1559    0.0
1560    0.0
1561    1.0
1562    1.0
1563    0.0
1564    0.0
1565    0.0
1566    1.0
1567    1.0
1568    0.0
1569    0.0
1570    0.0
1571    0.0
1572    0.0
1573    0.0
1574    0.0
1575    1.0
1576    0.0
1577    0.0
1578    0.0
1579    0.0
1580    1.0
1581    0.0
1582    0.0
1583    0.0
1584    0.0
1585    0.0
1586    1.0
1587    0.0
1588    1.0
1589    0.0
1590    0.0
1591    0.0
1592    0.0
1593    0.0
1594    0.0
1595    0.0
1596    1.0
1597    0.0
1598    0.0
1599    1.0
1600    0.0
1601    0.0
1602    0.0
1603    1.0
1604    0.0
1605    0.0
1606    0.0
1607    0.0
1608    0.0
1609    0.0
1610    1.0
1611    0.0
1612    0.0
1613    0.0
1614
1615    1.0
1616    1.0
1617    0.0
1618    0.0
1619    0.0
1620    0.0
1621    0.0
1622    0.0
1623    0.0
1624    1.0
1625    0.0
1626
1627    0.0
1628    0.0
1629    0.0
1630    0.0
1631    0.0
1632    1.0
1633    0.0
1634    0.0
1635    0.0
1636    0.0
1637    1.0
1638    0.0
1639    0.0
1640    1.0
1641    0.0
1642    0.0
1643    1.0
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1649    1.0
1650    0.0
1651    0.0
1652    1.0
1653    1.0
1654    1.0
1655    0.0
1656    0.0
1657    0.0
1658    1.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1666    1.0
1667    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0

In [17]:
# df.isna().sum()

**Join a column on top 5 primary banks**

In [18]:
def combine_columns_by_prefix(df, prefix, new_col_name, delimiter=';'):
    cols = [col for col in df.columns if col.startswith(prefix)]
    df[new_col_name] = df[cols].astype(str).apply(
        lambda row: delimiter.join(
            [val.strip() for val in row if val.strip().lower() != 'nan' and val.strip() != '']
        ),
        axis=1
    )
    return df

# Use it for both groups
df = combine_columns_by_prefix(df, "Please select your top 5 primary banks/e-wallet.", "top_5_combined")
df = combine_columns_by_prefix(df, "Please select your top 3 primary banks/e-wallet.", "top_3_combined")

In [19]:
df['top_3_combined'].head()

0                                             Seabank
1    BPI (Bank of the Philippine Islands);GoTyme Bank
2                               UnionBank;GoTyme Bank
3                           GoTyme Bank;Seabank;GCash
4                                         GoTyme Bank
Name: top_3_combined, dtype: object

**Combine banks with <30 primary banks to a single other column**

In [20]:
# Count how many responses each bank has
bank_counts = df["Which bank do you consider as your main primary bank? - Response"].value_counts()

# Identify banks to group
threshold = 40
low_count_banks = bank_counts[bank_counts < threshold].index.tolist()

# Ensure forced banks are included
group_as_other = list(set(low_count_banks))

# Apply new label for grouped banks
df["Which bank do you consider as your main primary bank? - Response"] = df[
    "Which bank do you consider as your main primary bank? - Response"
].apply(lambda x: "Other (CIMB Bank, Security Bank, PNB (Philippine National Bank), RCBC (Rizal Commercial Banking Corporation), China Bank, EastWest Bank, OwnBank, Tonik Bank, Overseas Bank (e.g., HSBC, Citibank, Standard Chartered))"
 if x in group_as_other else x)

**Check data consistency. If person picked a priamry bank, does he also have transaction with other banks even if it is not their primary bank**

In [21]:
def validate_primary_bank_transactions(df, main_col, transaction_prefix):
    # Step 1: Get all transaction columns
    transaction_cols = [col for col in df.columns if col.startswith(transaction_prefix)]

    # Step 2: Normalize main bank values (strip + lower)
    df['__main_bank_normalized'] = df[main_col].astype(str).str.strip().str.lower()

    # Step 3: Create normalized map of transaction columns
    col_map = {col: col.split(' - ')[-1].strip().lower() for col in transaction_cols}

    # Step 4: Validate each row
    def validate_row(row):
        main_bank = row['__main_bank_normalized']
        for col in transaction_cols:
            bank = col_map[col]
            val = row[col]
            # If it's the main bank, we allow any value
            if bank == main_bank:
                continue
            # If it's not the main bank but has a value, it's inconsistent
            if pd.notna(val) and str(val).strip() not in ["", "0", "nan"]:
                return False
        return True

    # Step 5: Apply the validation
    df['primary_bank_transaction_consistent'] = df.apply(validate_row, axis=1)

    # Step 6: Clean up
    df.drop(columns='__main_bank_normalized', inplace=True)

    return df

In [22]:
df = validate_primary_bank_transactions(
    df,
    main_col='Which bank do you consider as your main primary bank? - Response',
    transaction_prefix='How many transactions do you perform per month using your primary bank?'
)

In [23]:
df['primary_bank_transaction_consistent'].value_counts(normalize=True)

primary_bank_transaction_consistent
False    0.586437
True     0.413563
Name: proportion, dtype: float64

So 58% have inconsistent data. even if they didn't choose a particualr bank as their primary bank, they still answered the number of transaction on differnt non primary banks they have

In [24]:
df['How much is your usual balance in each bank? - GCash'].value_counts()

How much is your usual balance in each bank? - GCash
                           1719
P 1,001 - P 5,000           366
Less than P 1,000           312
P 5,001 - P 10,000          193
P 10,001 - P 20,000         120
P 20,001 - P 50,000          72
P 50,001 - P 100,000         42
P 100,001 - P 500,000        15
P 500,001 - P 1,000,000       7
Name: count, dtype: int64

**Make integer for how much is your usual balance in each bank**

In [25]:
def convert_currency_bins_to_midpoints(df):
    # Target columns for both balance and spending
    target_cols = [
        col for col in df.columns
        if col.startswith("How much is your usual balance in each bank?")
        or col.startswith("How much do you usually spend per month using your primary bank?")
    ]

    def bin_to_midpoint(value):
        if pd.isna(value) or value == "":
            return 0

        value = value.strip()

        # "Less than P 1,000" or "Below ₱5,000"
        match_less = re.match(r"(Less than|Below) [₱P] ?([\d,]+)", value)
        if match_less:
            max_val = int(match_less.group(2).replace(",", ""))
            return max_val // 2

        # "₱10,000 - ₱24,999" or "P 1,001 - P 5,000"
        match_range = re.match(r"[₱P] ?([\d,]+) ?- ?[₱P] ?([\d,]+)", value)
        if match_range:
            low = int(match_range.group(1).replace(",", ""))
            high = int(match_range.group(2).replace(",", ""))
            return (low + high) // 2

        # "₱250,000 and above"
        match_above = re.match(r"[₱P] ?([\d,]+) and above", value)
        if match_above:
            return int(match_above.group(1).replace(",", ""))

        # Single value fallback
        match_single = re.match(r"[₱P] ?([\d,]+)", value)
        if match_single:
            return int(match_single.group(1).replace(",", ""))

        # Fallback
        return 0

    # Apply transformation
    for col in target_cols:
        df[col] = df[col].apply(bin_to_midpoint).astype(int)

    return df

In [26]:
def convert_transaction_bins_to_midpoints(df):
    """
    Converts transaction count bins (e.g. '5 - 9 transactions') into integer midpoints.
    Affects only columns starting with:
    'How many transactions do you perform per month using your primary bank?'
    """
    # Select only relevant columns
    transaction_cols = [
        col for col in df.columns
        if col.startswith("How many transactions do you perform per month using your primary bank?")
    ]

    def transaction_bin_to_midpoint(value):
        if pd.isna(value) or value == "":
            return 0

        value = value.strip()

        # Handle "Less than X transactions"
        match_less = re.match(r"Less than ([\d,]+) transactions", value)
        if match_less:
            max_val = int(match_less.group(1).replace(",", ""))
            return max_val // 2

        # Handle "X - Y transactions"
        match_range = re.match(r"([\d,]+) ?- ?([\d,]+) transactions", value)
        if match_range:
            low = int(match_range.group(1).replace(",", ""))
            high = int(match_range.group(2).replace(",", ""))
            return (low + high) // 2

        # Handle "X or more transactions"
        match_or_more = re.match(r"([\d,]+) or more transactions", value)
        if match_or_more:
            return int(match_or_more.group(1).replace(",", ""))

        return 0

    # Apply transformation
    for col in transaction_cols:
        df[col] = df[col].apply(transaction_bin_to_midpoint).astype(int)

    return df

In [27]:
convert_currency_bins_to_midpoints(df)
convert_transaction_bins_to_midpoints(df)
pass

In [28]:
df['How much is your usual balance in each bank? - GCash'].value_counts()

How much is your usual balance in each bank? - GCash
0         1719
3000       366
500        312
7500       193
15000      120
35000       72
75000       42
300000      15
750000       7
Name: count, dtype: int64

In [29]:
df[ 'How much do you usually spend per month using your primary bank? (Include expenses like bills payment, transfers, online/offline purchases, subscriptions, etc.) - BDO Unibank'].value_counts()

How much do you usually spend per month using your primary bank? (Include expenses like bills payment, transfers, online/offline purchases, subscriptions, etc.) - BDO Unibank
0         2559
2500        91
17499       71
37499       45
7499        42
74999       20
174999      11
250000       7
Name: count, dtype: int64

In [30]:
df['How many transactions do you perform per month using your primary bank? (Include fund transfers, ATM withdrawals, bills payments, purchases, loan payments, etc.) - BDO Unibank'].value_counts()

How many transactions do you perform per month using your primary bank? (Include fund transfers, ATM withdrawals, bills payments, purchases, loan payments, etc.) - BDO Unibank
0      2560
2       111
7        88
14       54
34       21
74        6
100       6
Name: count, dtype: int64

**Sum the balance, transaction, and spend**

In [31]:
def compute_totals(df):
    # 1. Total balance across all banks
    balance_cols = [col for col in df.columns if col.startswith("How much is your usual balance in each bank?")]
    df["total_balance_all_banks"] = df[balance_cols].sum(axis=1)

    # 2. Total spend per month across all banks
    spend_cols = [col for col in df.columns if col.startswith("How much do you usually spend per month using your primary bank?")]
    df["total_spend_all_banks"] = df[spend_cols].sum(axis=1)

    # 3. Total number of transactions per month across all banks
    transaction_cols = [col for col in df.columns if col.startswith("How many transactions do you perform per month using your primary bank?")]
    df["total_transactions_all_banks"] = df[transaction_cols].sum(axis=1)

In [32]:
compute_totals(df)

In [33]:
df['total_balance_all_banks'].value_counts(normalize=True)

total_balance_all_banks
0          0.253689
3000       0.044624
15000      0.042516
7500       0.035840
500        0.026353
35000      0.021434
1500       0.018974
9000       0.017569
18000      0.016866
11000      0.016163
4000       0.015109
30000      0.015109
6000       0.014758
22500      0.014758
1000       0.014055
50000      0.014055
6500       0.013352
3500       0.011947
57500      0.011595
13500      0.011595
25500      0.011244
10500      0.010541
75000      0.009838
8500       0.009487
21000      0.009136
65000      0.009136
53000      0.009136
105000     0.008784
18500      0.008433
15500      0.008082
45000      0.007730
125000     0.007027
900000     0.007027
145000     0.007027
45500      0.007027
37500      0.006676
42500      0.006676
33000      0.006676
23000      0.006676
38500      0.006325
41000      0.005622
77500      0.005622
73000      0.005271
85000      0.005271
78500      0.004919
410000     0.004919
16000      0.004919
110500     0.004568
85500      0.004568
300000     0.004568
225000     0.004216
90000      0.004216
113000     0.004216
97500      0.003865
8000       0.003865
370000     0.003865
81000      0.003865
450000     0.003514
117500     0.003514
70000      0.003514
675000     0.003514
157500     0.003514
38000      0.003514
43000      0.003162
338000     0.003162
70500      0.003162
1350000    0.003162
50500      0.003162
378000     0.003162
110000     0.003162
185000     0.003162
382500     0.002811
36000      0.002811
322500     0.002811
315000     0.002811
165000     0.002460
318000     0.002460
35500      0.002460
93000      0.002460
635000     0.002108
375001     0.002108
375000     0.002108
153000     0.001757
350000     0.001757
750000     0.001757
90500      0.001757
342500     0.001757
1125000    0.001757
150000     0.001405
607500     0.001405
603000     0.001405
600500     0.001405
30500      0.001405
330000     0.001405
78000      0.001405
1          0.001405
390000     0.001405
600001     0.001054
307500     0.001054
1050001    0.001054
315500     0.001054
82500      0.001054
310500     0.001054
615000     0.001054
335000     0.001054
303500     0.000703
75500      0.000703
335001     0.000703
1800000    0.000703
83000      0.000703
76000      0.000703
760500     0.000703
308000     0.000703
1535000    0.000703
3          0.000703
150500     0.000703
600000     0.000703
300500     0.000703
306000     0.000703
6001       0.000703
303000     0.000351
1065000    0.000351
24500      0.000351
678000     0.000351
1575000    0.000351
90001      0.000351
1085000    0.000351
750002     0.000351
825500     0.000351
1053000    0.000351
150001     0.000351
300002     0.000351
120500     0.000351
1050000    0.000351
7502       0.000351
2250000    0.000351
75501      0.000351
301000     0.000351
315001     0.000351
19000      0.000351
335500     0.000351
840000     0.000351
307501     0.000351
750001     0.000351
15002      0.000351
825000     0.000351
772500     0.000351
1500000    0.000351
757500     0.000351
1500001    0.000351
375500     0.000351
110001     0.000351
800000     0.000351
313500     0.000351
1001       0.000351
501        0.000351
Name: proportion, dtype: float64

**Create profile_df**

In [34]:
profile_df = df.copy()

# Profile with nps data

In [35]:
df = raw_df.copy()

In [36]:
def load_column_0_and_130_onward(file_path):
    # Read just the header to get all column names
    all_cols = pd.read_csv(file_path, nrows=0).columns.tolist()

    # Pick column 0 and columns from index 130 onward
    selected_indices = [0] + list(range(126, len(all_cols)))

    # Get the column names at those indices
    selected_cols = [all_cols[i] for i in selected_indices]

    # Load only those columns
    df = pd.read_csv(file_path, usecols=selected_cols)

    return df

In [45]:
df = load_column_0_and_130_onward('T-NPS.csv')

**Rename questions to qn (q1,q2, etc.)**

In [46]:
def rename_unnamed_columns(df):
    new_columns = []
    q_counter = 11
    current_q = None

    for col in df.columns:
        if col == 'Respondent ID':
            new_columns.append(col)
        elif not col.startswith("Unnamed"):
            # It's a real question, assign a new q label
            current_q = f"q{q_counter}"
            q_counter += 1
            new_columns.append(current_q)
        else:
            # It's unnamed, attach to the last valid q group
            if current_q is not None:
                new_columns.append(current_q)
            else:
                new_columns.append("unknown")  # Fallback for leading unnamed columns

    df.columns = new_columns

In [47]:
rename_unnamed_columns(df)

In [48]:
df.columns

Index(['Respondent ID', 'q11', 'q11', 'q11', 'q11', 'q11', 'q11', 'q11', 'q12',
       'q12', 'q12', 'q12', 'q12', 'q13', 'q13', 'q13', 'q13', 'q13', 'q14',
       'q14', 'q14', 'q14', 'q15', 'q15', 'q15', 'q15', 'q15', 'q15', 'q16',
       'q17', 'q18', 'q18', 'q18', 'q18', 'q18', 'q18', 'q18', 'q19', 'q19',
       'q19', 'q19', 'q19', 'q20', 'q20', 'q20', 'q20', 'q21', 'q21', 'q21',
       'q21', 'q21', 'q22', 'q22', 'q22', 'q22', 'q23', 'q23', 'q23', 'q23',
       'q23', 'q23', 'q24', 'q24', 'q24', 'q24', 'q24', 'q24', 'q24', 'q25',
       'q25', 'q25', 'q25', 'q25', 'q25', 'q25', 'q25', 'q26', 'q27', 'q28',
       'q29', 'q30', 'q31'],
      dtype='object')

# TODO

In [40]:
# # Count how many responses each bank has
# bank_counts = df['How do you define your primary bank? (Select all that apply)Paano mo inilalarawan ang iyong pangunahing bangko?'].value_counts()

# # Identify banks to group
# threshold = 40
# low_count_banks = bank_counts[bank_counts < threshold].index.tolist()

# # Ensure forced banks are included
# group_as_other = list(set(low_count_banks))

# # Apply new label for grouped banks
# df['How do you define your primary bank? (Select all that apply)Paano mo inilalarawan ang iyong pangunahing bangko?'] = df[
#     'How do you define your primary bank? (Select all that apply)Paano mo inilalarawan ang iyong pangunahing bangko?'
# ].apply(lambda x: "Other (CIMB Bank, Security Bank, PNB (Philippine National Bank), RCBC (Rizal Commercial Banking Corporation), China Bank, EastWest Bank, OwnBank, Tonik Bank, Overseas Bank (e.g., HSBC, Citibank, Standard Chartered))"
#  if x in group_as_other else x)

KeyError: 'How do you define your primary bank? (Select all that apply)Paano mo inilalarawan ang iyong pangunahing bangko?'

**Combine column header and first row**

In [ ]:

    # Extract the first row as a list
label_row = df.iloc[0].tolist()

    # Build new column names by combining column header and label
new_columns = []
for col, label in zip(df.columns, label_row):
      col_str = str(col).strip()
      label_str = str(label).strip() if pd.notna(label) and str(label).strip().lower() != "nan" else ""

      if label_str:
          new_col = f"{col_str} - {label_str}"
      else:
          new_col = col_str

      new_columns.append(new_col)

    # Apply new column names
df.columns = new_columns

    # Drop the label row
df = df.iloc[1:].reset_index(drop=True)

    # Optional: Try converting columns to numeric where appropriate
df = df.apply(pd.to_numeric, errors='ignore')

**q30 - combine to 500k and above**

In [ ]:
def simplify_income_bracket(value):
    if value in [
        'PHP500,001 - PHP750,000',
        'PHP750,001 - PHP1.0M',
        'PHP1.01M - PHP1.99M',
        'PHP2.0M and above'
    ]:
        return 'PHP500,001 and above'
    return value

# Apply the transformation
df['q30 - Adjusted'] = df['q30 - Response'].apply(simplify_income_bracket)

# Get updated counts
income_counts = df['q30 - Response'].value_counts().sort_index()

**Mid point of salary (q30) to integer**

In [ ]:
def get_midpoint(val):
    if not isinstance(val, str):
        return None  # or np.nan or any default you prefer

    if 'Below' in val:
        return 4000
    if 'and above' in val:
        return 500001

    # Extract numeric bounds using regex
    nums = re.findall(r'PHP([\d,]+)', val)
    if len(nums) == 2:
        low, high = [int(x.replace(',', '')) for x in nums]
        return int((low + high) / 2)

    return None

# Create a new column with integer midpoints
df['q30 - Integer'] = df['q30 - Adjusted'].apply(get_midpoint)

**Turn likert to number**

In [ ]:
def convert_nps_columns_to_int(df):
    target_prefixes = ("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24")

    for col in df.columns:
        if col.startswith(target_prefixes):
            def extract_score(val):
                if pd.isna(val) or str(val).strip() == "":
                    return pd.NA
                match = re.match(r"(\d+)", str(val).strip())
                return int(match.group(1)) if match else pd.NA

            df[col] = df[col].apply(extract_score)

    return df

**Compute for NPS**

In [ ]:
def compute_nps(df):
    target_prefixes = ("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24")
    nps_results = []

    for col in df.columns:
        if col.startswith(target_prefixes):
            # Work on a temporary copy of the column
            temp_series = pd.to_numeric(df[col], errors='coerce')

            # Drop only nulls for calculation, do not affect original df
            valid_responses = temp_series.dropna().astype(int)

            total_responses = len(valid_responses)
            promoters = (valid_responses >= 9).sum()
            passives = ((valid_responses >= 7) & (valid_responses <= 8)).sum()
            detractors = (valid_responses <= 6).sum()

            if total_responses == 0:
                nps_score = None
            else:
                nps_score = ((promoters - detractors) / total_responses) * 100

            # Print detailed computation
            print(f"\n📊 NPS Calculation for {col}")
            print(f"Total Responses: {total_responses}")
            print(f"Promoters (9–10): {promoters}")
            print(f"Passives (7–8): {passives}")
            print(f"Detractors (0–6): {detractors}")
            if nps_score is not None:
                print(f"NPS = (({promoters} - {detractors}) / {total_responses}) * 100 = {nps_score:.2f}")
            else:
                print("No valid responses available for calculation.")

            # Store the result
            nps_results.append({
                "Question": col,
                "Total Responses": total_responses,
                "Promoters": promoters,
                "Passives": passives,
                "Detractors": detractors,
                "NPS": round(nps_score, 2) if nps_score is not None else None
            })

    return pd.DataFrame(nps_results)

In [ ]:
df = convert_nps_columns_to_int(df)
nps_df = compute_nps(df)

In [ ]:
nps_df

In [ ]:
df['q12 - I feel SECURED whenever I use GoTyme Bank.(Secured ako sa tuwing ginagamit ko ang GoTyme Bank.)'].value_counts()

**Make copy of likert df**

In [ ]:
likert_df = df.copy()

**Merge likert and profile df**

In [ ]:
merged_df = pd.merge(profile_df, likert_df, on='Respondent ID', how='inner')  # or 'outer', 'left', 'right'

In [ ]:
merged_df.head(3)

**NPS per bank**

**NPS per primary bank**

In [ ]:
def compute_nps_by_primary_bank(df,
                                 prefixes=("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24"),
                                 primary_bank_column='Which bank do you consider as your main primary bank? - Response'):
    results = []

    # Iterate through all NPS prefixes
    for prefix in prefixes:
        nps_columns = [col for col in df.columns if col.startswith(prefix)]

        for nps_col in nps_columns:
            for bank in df[primary_bank_column].dropna().unique():
                sub_df = df[df[primary_bank_column] == bank]

                # Safely convert to numeric, ignore invalid entries
                valid_scores = pd.to_numeric(sub_df[nps_col], errors='coerce').dropna()

                if valid_scores.empty:
                    continue

                promoters = (valid_scores >= 9).sum()
                passives = ((valid_scores >= 7) & (valid_scores <= 8)).sum()
                detractors = (valid_scores <= 6).sum()
                total = len(valid_scores)
                nps = ((promoters - detractors) / total) * 100

                # Print details
                # print(f"\n📊 {nps_col} - NPS for {bank}")
                # print(f"Total Responses: {total}")
                # print(f"Promoters (9-10): {promoters}")
                # print(f"Passives (7-8): {passives}")
                # print(f"Detractors (0-6): {detractors}")
                # print(f"NPS = (({promoters} - {detractors}) / {total}) * 100 = {nps:.2f}")

                results.append({
                    "Question": nps_col,
                    "Bank": bank,
                    "Total Responses": total,
                    "Promoters": promoters,
                    "Passives": passives,
                    "Detractors": detractors,
                    "NPS": round(nps, 2)
                })

    return pd.DataFrame(results)

In [ ]:
nps_by_bank_all = compute_nps_by_primary_bank(merged_df)

In [ ]:
nps_by_bank_all.head(10)

**NPS Based on top3 and top5**

In [ ]:
def compute_nps_by_top5_bank(df,
                              top5_column='top_5_combined',
                              prefixes=("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24"),
                              bank_list=None):
    results = []

    df[top5_column] = df[top5_column].fillna("").astype(str)

    # Build bank list if not given
    if bank_list is None:
        bank_list = set()
        for entry in df[top5_column]:
            bank_list.update([b.strip() for b in entry.split(';') if b.strip()])
        bank_list = sorted(bank_list)

    def bank_in_top5(row_banks, target_bank):
        return target_bank in [b.strip() for b in row_banks.split(';') if b.strip()]

    for prefix in prefixes:
        nps_columns = [col for col in df.columns if col.startswith(prefix)]

        for nps_col in nps_columns:
            for bank in bank_list:
                # Filter rows where bank is in their top_5_combined list
                mask = df[top5_column].apply(lambda x: bank_in_top5(x, bank))
                valid_scores = pd.to_numeric(df.loc[mask, nps_col], errors='coerce').dropna()

                if valid_scores.empty:
                    continue

                promoters = (valid_scores >= 9).sum()
                passives = ((valid_scores >= 7) & (valid_scores <= 8)).sum()
                detractors = (valid_scores <= 6).sum()
                total = len(valid_scores)
                nps = ((promoters - detractors) / total) * 100

                results.append({
                    "Question": nps_col,
                    "Bank": bank,
                    "Total Responses": total,
                    "Promoters": promoters,
                    "Passives": passives,
                    "Detractors": detractors,
                    "NPS": round(nps, 2)
                })

    return pd.DataFrame(results)

In [ ]:
df_nps_top5 = compute_nps_by_top5_bank(merged_df)
df_nps_top5['Bank'].value_counts()

**NPS per top3**

In [ ]:
def compute_nps_by_top3_bank(df,
                              top3_column='top_3_combined',
                              prefixes=("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24"),
                              bank_list=None):
    results = []

    df[top3_column] = df[top3_column].fillna("").astype(str)

    # Build bank list if not given
    if bank_list is None:
        bank_list = set()
        for entry in df[top3_column]:
            bank_list.update([b.strip() for b in entry.split(';') if b.strip()])
        bank_list = sorted(bank_list)

    def bank_in_top3(row_banks, target_bank):
        return target_bank in [b.strip() for b in row_banks.split(';') if b.strip()]

    for prefix in prefixes:
        nps_columns = [col for col in df.columns if col.startswith(prefix)]

        for nps_col in nps_columns:
            for bank in bank_list:
                # Filter rows where bank is in their top_3_combined list
                mask = df[top3_column].apply(lambda x: bank_in_top3(x, bank))
                valid_scores = pd.to_numeric(df.loc[mask, nps_col], errors='coerce').dropna()

                if valid_scores.empty:
                    continue

                promoters = (valid_scores >= 9).sum()
                passives = ((valid_scores >= 7) & (valid_scores <= 8)).sum()
                detractors = (valid_scores <= 6).sum()
                total = len(valid_scores)
                nps = ((promoters - detractors) / total) * 100

                results.append({
                    "Question": nps_col,
                    "Bank": bank,
                    "Total Responses": total,
                    "Promoters": promoters,
                    "Passives": passives,
                    "Detractors": detractors,
                    "NPS": round(nps, 2)
                })

    return pd.DataFrame(results)

In [ ]:
df_nps_top3 = compute_nps_by_top3_bank(merged_df)
df_nps_top3.head(20)

**NPS Based on q16 - have you encountered security related issues**

In [ ]:
def compute_nps_by_group_column(df,
                                 group_column='q16 - Response',
                                 prefixes=("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24")):
    results = []

    df[group_column] = df[group_column].fillna("").astype(str)
    group_values = df[group_column].unique()

    for prefix in prefixes:
        nps_columns = [col for col in df.columns if col.startswith(prefix)]

        for nps_col in nps_columns:
            for group_value in group_values:
                sub_df = df[df[group_column] == group_value]
                valid_scores = pd.to_numeric(sub_df[nps_col], errors='coerce').dropna()

                if valid_scores.empty:
                    continue

                promoters = (valid_scores >= 9).sum()
                passives = ((valid_scores >= 7) & (valid_scores <= 8)).sum()
                detractors = (valid_scores <= 6).sum()
                total = len(valid_scores)
                nps = ((promoters - detractors) / total) * 100

                results.append({
                    "Question": nps_col,
                    group_column: group_value,
                    "Total Responses": total,
                    "Promoters": promoters,
                    "Passives": passives,
                    "Detractors": detractors,
                    "NPS": round(nps, 2)
                })

    return pd.DataFrame(results)

In [ ]:
nps_by_q16 = compute_nps_by_group_column(df, group_column='q16 - Response')

**NPS on q30 - monthly income**

In [ ]:
nps_by_q30 = compute_nps_by_group_column(df, group_column='q30 - Adjusted')

In [ ]:
nps_by_q30.head(10)

**NPS based on q29 - Response**

In [ ]:
nps_by_q29 = compute_nps_by_group_column(df, group_column='q29 - Response')

In [ ]:
nps_by_q29.head(30)

**NPS per q29 and q30**

In [ ]:
def compute_nps_by_multigroup(df,
                               group_columns=None,
                               prefixes=("q12", "q13", "q14", "q15", "q19", "q20", "q21", "q22", "q23", "q24")):
    results = []

    # Normalize group_columns to tuple if it's a string
    if isinstance(group_columns, str):
        group_columns = (group_columns,)
    elif group_columns is None:
        group_columns = ()

    # Fill missing values in group columns
    for col in group_columns:
        df[col] = df[col].fillna("").astype(str)

    # If there are group columns, get unique combinations
    group_combinations = df[list(group_columns)].drop_duplicates() if group_columns else [None]

    for prefix in prefixes:
        nps_columns = [col for col in df.columns if col.startswith(prefix)]

        for nps_col in nps_columns:
            if group_columns:
                for _, group_vals in group_combinations.iterrows():
                    mask = pd.Series(True, index=df.index)
                    for col in group_columns:
                        mask &= df[col] == group_vals[col]
                    sub_df = df[mask]

                    valid_scores = pd.to_numeric(sub_df[nps_col], errors='coerce').dropna()
                    if valid_scores.empty:
                        continue

                    promoters = (valid_scores >= 9).sum()
                    passives = ((valid_scores >= 7) & (valid_scores <= 8)).sum()
                    detractors = (valid_scores <= 6).sum()
                    total = len(valid_scores)
                    nps = ((promoters - detractors) / total) * 100

                    result = {
                        "Question": nps_col,
                        "Total Responses": total,
                        "Promoters": promoters,
                        "Passives": passives,
                        "Detractors": detractors,
                        "NPS": round(nps, 2)
                    }
                    for col in group_columns:
                        result[col] = group_vals[col]
                    results.append(result)
            else:
                # No grouping: compute over full dataframe
                valid_scores = pd.to_numeric(df[nps_col], errors='coerce').dropna()
                if valid_scores.empty:
                    continue

                promoters = (valid_scores >= 9).sum()
                passives = ((valid_scores >= 7) & (valid_scores <= 8)).sum()
                detractors = (valid_scores <= 6).sum()
                total = len(valid_scores)
                nps = ((promoters - detractors) / total) * 100

                result = {
                    "Question": nps_col,
                    "Total Responses": total,
                    "Promoters": promoters,
                    "Passives": passives,
                    "Detractors": detractors,
                    "NPS": round(nps, 2)
                }
                results.append(result)

    return pd.DataFrame(results)

In [ ]:
nps_by_q29_q30 = compute_nps_by_multigroup(df, group_columns=["q29 - Response", "q30 - Integer"])

In [ ]:
nps_by_q29_q30.head(30)

# Download NPS tables

In [ ]:
# import os
# from google.colab import files

# # Save each DataFrame as a CSV in that folder
# nps_dfs = {
#     'NPS_per_primary_bank.csv': nps_by_bank_all,
#     'NPS_per_top5_bank.csv': df_nps_top5,
#     'NPS_per_top3_bank.csv': df_nps_top3,
#     'NPS_per_q16_security_issues.csv': nps_by_q16,
#     'NPS_per_q29_employment.csv': nps_by_q30,
#     'NPS_per_q30_income.csv': nps_by_q29,
#       'NPS_general.csv': nps_df
# }

# for filename, df in nps_dfs.items():
#     df.to_csv(f'{filename}', index=False)
#     files.download(filename)

# Analysis

In [ ]:
import seaborn as sns

In [ ]:
# df[['Which bank do you consider as your main primary bank? - Response',
#  'top_5_combined',
#  'top_3_combined']].head()

In [ ]:
# sns.scatterplot(data=df, x='total_balance_all_banks', y = 'total_spend_all_banks')

**Scatter plot on NPS employment**

In [ ]:
# import matplotlib.pyplot as plt

# plt.figure(figsize=(12, 6))

# sns.scatterplot(
#     data=plot_df,
#     x='q30_integer',
#     y='NPS',
#     hue='q29_filled',
#     size='Total Responses',
#     sizes=(50, 500),  # adjust size range
#     palette='Set2',
#     alpha=0.8,
#     edgecolor='black'
# )

# plt.xlabel('Income Bracket Midpoint (PHP)')
# plt.ylabel('Net Promoter Score (NPS)')
# plt.title('NPS vs. Income Level (Bubble size = Response count)')
# plt.legend(title='q29 - Response', bbox_to_anchor=(1.05, 1), loc='upper left')
# plt.grid(True, linestyle='--', alpha=0.5)
# plt.tight_layout()
# plt.show()

In [ ]:
# avg_nps_by_income = plot_df.groupby('q30_integer')['NPS'].mean().sort_index()

# avg_nps_by_income.plot(kind='bar', figsize=(12, 6), color='skyblue', edgecolor='black')
# plt.ylabel('Average NPS')
# plt.xlabel('Income Bracket Midpoint (PHP)')
# plt.title('Average NPS by Income Bracket')
# plt.xticks(rotation=45)
# plt.grid(axis='y', linestyle='--', alpha=0.5)
# plt.tight_layout()
# plt.show()

# Feature Engineer for ML

**Create nps table that has q30, q16, transaction, spending, primary bank, job**

In [ ]:
# nps_linear_reg = compute_nps_by_multigroup(merged_df, group_columns=["q29 - Response", "q30 - Adjusted", 'q16 - Response', 'Which bank do you consider as your main primary bank? - Response', 'total_balance_all_banks',
#                                                                      'total_spend_all_banks', 'total_transactions_all_banks'])

In [ ]:
# nps_linear_reg.shape

**download nps_linear_reg**

In [ ]:
# # Save the DataFrame to a CSV file
# nps_linear_reg.to_csv('nps_linear_reg.csv', index=False)

# # Download the file
# from google.colab import files
# files.download('nps_linear_reg.csv')

**read nps_linear_reg**

In [ ]:
nps_linear_reg = pd.read_csv('nps_linear_reg.csv')

In [ ]:
# nps_linear_reg['total_spend_all_banks'].value_counts()

In [ ]:
nps_linear_reg.head(10)

# Data Preprocessing

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans

In [ ]:
def cluster_users(df, n_clusters=4):
    working_df = df.copy()

    # Map binary question safely
    working_df["q16 - Response"] = working_df["q16 - Response"].map({"Yes": 1, "No": 0})

    # Drop rows with missing critical fields BEFORE encoding
    required_columns = [
        "NPS",
        "total_balance_all_banks",
        "total_spend_all_banks",
        "total_transactions_all_banks",
        "q16 - Response",
        "q29 - Response",
        "q30 - Adjusted",
    ]
    working_df = working_df.dropna(subset=required_columns)

    # Encode employment, income, bank
    le_employment = LabelEncoder()
    working_df["employment_encoded"] = le_employment.fit_transform(working_df["q29 - Response"])

    le_income = LabelEncoder()
    working_df["income_encoded"] = le_income.fit_transform(working_df["q30 - Adjusted"])

    # Final features for clustering
    clustering_features = working_df[[
        "NPS",
        "total_balance_all_banks",
        "total_spend_all_banks",
        "total_transactions_all_banks",
        "q16 - Response",
        "employment_encoded",
        "income_encoded",
    ]]

    # Re-check and drop rows with NaNs if any remain
    clustering_features = clustering_features.dropna()

    # Standardize features
    scaler = StandardScaler()
    scaled = scaler.fit_transform(clustering_features)

    # Run KMeans
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    working_df["Cluster"] = kmeans.fit_predict(scaled)

    # Summary
    summary = working_df.groupby("Cluster").mean(numeric_only=True)
    counts = working_df["Cluster"].value_counts().sort_index()

    print("\n📊 Cluster Sizes:")
    print(counts)

    print("\n📉 Cluster Feature Averages:")
    print(summary)

    return working_df, summary

In [ ]:
working_df, summary = cluster_users(nps_linear_reg)

# Get label encoding for better interpretation

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_employment = LabelEncoder()
nps_linear_reg['employment_encoded'] = le_employment.fit_transform(nps_linear_reg['q29 - Response'])

le_income = LabelEncoder()
nps_linear_reg['income_encoded'] = le_income.fit_transform(nps_linear_reg['q30 - Adjusted'])

le_bank = LabelEncoder()
nps_linear_reg['bank_encoded'] = le_bank.fit_transform(nps_linear_reg['Which bank do you consider as your main primary bank? - Response'])

In [ ]:
# Employment mapping
employment_mapping = dict(zip(le_employment.classes_, le_employment.transform(le_employment.classes_)))
print("Employment Mapping:")
print(employment_mapping)

# Income mapping
income_mapping = dict(zip(le_income.classes_, le_income.transform(le_income.classes_)))
print("\nIncome Mapping:")
print(income_mapping)

# Bank mapping
bank_mapping = dict(zip(le_bank.classes_, le_bank.transform(le_bank.classes_)))
print("\nBank Mapping:")
print(bank_mapping)

In [ ]:
# Employment mapping
print("\nEmployment Mapping:")
print(nps_linear_reg[['employment_encoded', 'q29 - Response']].dropna().drop_duplicates().sort_values('employment_encoded'))

# Income mapping
print("\nIncome Mapping:")
print(nps_linear_reg[['income_encoded', 'q30 - Adjusted']].dropna().drop_duplicates().sort_values('income_encoded'))

# # Bank mapping
# print("\nBank Mapping:")
# print(nps_linear_reg[['bank_encoded', 'Which bank do you consider as your main primary bank? - Response']].dropna().drop_duplicates().sort_values('bank_encoded'))

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

def plot_elbow_curve(data, max_k=10):
    sse = []  # Sum of Squared Errors
    for k in range(1, max_k + 1):
        km = KMeans(n_clusters=k, random_state=42)
        km.fit(data)
        sse.append(km.inertia_)

    plt.figure(figsize=(8, 5))
    plt.plot(range(1, max_k + 1), sse, marker='o')
    plt.xlabel('Number of Clusters (k)')
    plt.ylabel('SSE (Inertia)')
    plt.title('📈 Elbow Method for Optimal k')
    plt.grid(True)
    plt.show()

In [ ]:
features = [
    "Total Responses", "Promoters", "Passives", "Detractors", "NPS",
    "q16 - Response", "employment_encoded", "income_encoded"
]
data_for_clustering = working_df[features]

In [ ]:
plot_elbow_curve(data_for_clustering)

**For interpretation purposes, i think it is better if we use 4 clusters**

In [ ]:
working_df, summary = cluster_users(nps_linear_reg, n_clusters = 3)

In [ ]:
from sklearn.decomposition import PCA
import seaborn as sns

def visualize_clusters(data, labels):
    pca = PCA(n_components=2)
    reduced = pca.fit_transform(data)

    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=reduced[:, 0], y=reduced[:, 1], hue=labels, palette='tab10', alpha=0.7)
    plt.title('🧠 2D Cluster Visualization (PCA)')
    plt.xlabel('PCA 1')
    plt.ylabel('PCA 2')
    plt.legend(title='Cluster')
    plt.grid(True)
    plt.show()

In [ ]:
from sklearn.cluster import KMeans

# Fit clustering
kmeans = KMeans(n_clusters=4, random_state=42)
labels = kmeans.fit_predict(data_for_clustering)

# Visualize
visualize_clusters(data_for_clustering, labels)

# Clustering

In [ ]:
# import seaborn as sns
# import numpy as np
# sns.histplot(nps_linear_reg['total_balance_all_banks'], kde=True)
# sns.histplot(np.log1p(nps_linear_reg['total_balance_all_banks']), kde=True)

# Regression

In [ ]:
nps_linear_reg = pd.read_csv("nps_linear_reg.csv")

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import statsmodels.api as sm
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import statsmodels.api as sm

def run_nps_regression(df):
    working_df = df.copy()

    # Binary mapping for q16
    working_df["q16 - Response"] = working_df["q16 - Response"].map({"Yes": 1, "No": 0})

    # Drop rows with missing critical values
    required_cols = [
        "NPS",
        "q30 - Adjusted",
        "q29 - Response",
        "q16 - Response",
        "total_balance_all_banks",
        "total_spend_all_banks",
        "total_transactions_all_banks",
        'Which bank do you consider as your main primary bank? - Response'
    ]
    working_df = working_df.dropna(subset=required_cols)

    # One-hot encode categorical features
    categorical_features = ["q29 - Response", "q30 - Adjusted", 'Which bank do you consider as your main primary bank? - Response']
    encoder = OneHotEncoder(drop="first", sparse_output=False, dtype=int)
    encoded_cat = encoder.fit_transform(working_df[categorical_features])
    encoded_df = pd.DataFrame(
        encoded_cat,
        columns=encoder.get_feature_names_out(categorical_features),
        index=working_df.index
    )

    # Select numeric columns and concatenate
    numeric_features = working_df[[
        "q16 - Response",
        "total_balance_all_banks",
        "total_spend_all_banks",
        "total_transactions_all_banks"
    ]].astype(float)  # Ensure float type

    X = pd.concat([encoded_df, numeric_features], axis=1)
    y = working_df["NPS"].astype(float)

    # Drop any remaining NaNs or infs
    X = X.replace([np.inf, -np.inf], np.nan).dropna()
    y = y.loc[X.index]  # Align y with cleaned X

    # Add constant for intercept
    X = sm.add_constant(X)

    # Run OLS regression
    model = sm.OLS(y, X).fit()
    print(model.summary())

    return model

In [ ]:
model = run_nps_regression(nps_linear_reg)

In [ ]:
nps_linear_reg.columns.to_list()

In [ ]:
merged_df['Which bank do you consider as your main primary bank? - Response'].value_counts()

In [ ]:
df_nps_top5.head(30)